// Original A1 teaching material. French targets retain accents; Chinese explains the task.
export const units = [
  {
    id: 'fr01', title: '你好，法语', goal: '打招呼、礼貌表达、自我介绍',
    grammar: '法语句首大写，句末用标点。je 是“我”，vous 可礼貌地表示“您”，tu 用于熟人。je + 元音常缩写成 j’：Je m’appelle Léa（我叫 Léa）。être（是）的现在时：je suis、tu es、il/elle est、nous sommes、vous êtes、ils/elles sont。',
    pronunciation: '先听再模仿：bonjour 中的 on 是鼻化元音；salut 的末尾 t 通常不发音。é、è 会影响元音读音，不能随意去掉重音符号。法语 r 与汉语 r 不同；本课程用听辨和跟读练习，不自动评分发音。',
    vocabulary: [['bonjour','你好（白天，较正式）'],['salut','嗨（熟人之间）'],['au revoir','再见'],['merci','谢谢'],["s'il vous plaît",'请（礼貌用语）'],['oui','是的'],['non','不是／不'],['pardon','对不起／请再说一遍']],
    sentence: "Je m'appelle Léa.", sentenceMeaning: '我叫 Léa。',
    translate: ['我是 Paul。', ['Je suis Paul.']],
    grammarChoice: ['礼貌地向陌生人问好，选哪个？', ['Bonjour !','Salut, mon pote !','Bonne nuit !'], 'Bonjour !', 'Bonjour 适用于白天的礼貌问候；salut 更随意，bonne nuit 是晚安。'],
    grammarText: ['补全：Je ___ Léa.（我是 Léa。）', ['suis'], 'être 与 je 搭配使用 suis。'],
    listen: ['Bonjour ! Je m’appelle Hugo.', '说话者叫什么？', ['Hugo','Léa','Paul'], 'Hugo'],
    dictation: ['Merci.', ['Merci.']],
    reading: ['Bonjour. Je suis Léa. Je suis française. Au revoir !', 'Léa 在最后做了什么？', ['道别','询问价格','点餐'], '道别'],
    reviewGrammar: ['补全：Vous ___ Paul ?（您是 Paul 吗？）', ['êtes'], 'vous 对应 êtes。问句也可保留陈述句词序，通过语调提问。'],
    examAudio: ['Bonjour, je m’appelle Paul. Merci et au revoir.', '录音里出现的是哪种结束语？', ['Au revoir.','À demain.','Bonne nuit.'], 'Au revoir.']
  },
  {
    id: 'fr02', title: '介绍自己', goal: '年龄、国籍、职业与数字',
    grammar: '表达年龄用 avoir（有）：J’ai vingt ans（我20岁），不是 Je suis vingt。avoir：j’ai、tu as、il/elle a、nous avons、vous avez、ils/elles ont。职业在 être 后通常不加冠词：Je suis médecin。国籍形容词常随性别变化：français/française、chinois/chinoise。来自某地：Je viens de Chine。',
    pronunciation: '数字先慢读再连读。1–10：un, deux, trois, quatre, cinq, six, sept, huit, neuf, dix；11–16：onze, douze, treize, quatorze, quinze, seize；17–19 用 dix-sept 等；20/30/40/50/60 是 vingt/trente/quarante/cinquante/soixante，70 是 soixante-dix，80 是 quatre-vingts，90 是 quatre-vingt-dix，100 是 cent。vingt et un 表示21。听年龄时尤其注意 deux 与 douze。',
    vocabulary: [['étudiant','男学生'],['étudiante','女学生'],['médecin','医生'],['français','法国的／法语'],['chinois','中国的／汉语'],['vingt','二十'],['trente','三十'],['cent','一百']],
    sentence: "J'ai vingt ans.", sentenceMeaning: '我二十岁。',
    translate: ['我是一名医生。', ['Je suis médecin.']],
    grammarChoice: ['“她二十岁”应该怎么说？', ['Elle a vingt ans.','Elle est vingt ans.','Elle ont vingt ans.'], 'Elle a vingt ans.', '年龄用 avoir；elle 对应 a。'],
    grammarText: ['补全：Nous ___ trente ans.（我们三十岁。）', ['avons'], 'avoir 与 nous 对应 avons。'],
    listen: ['Je m’appelle Marie. J’ai trente ans. Je suis médecin.', 'Marie 几岁？', ['三十岁','十三岁','二十岁'], '三十岁'],
    dictation: ['Vingt.', ['vingt']],
    reading: ['Je suis Li. Je viens de Chine. Je suis étudiant. J’ai vingt ans.', 'Li 的职业／身份是什么？', ['学生','医生','教师'], '学生'],
    reviewGrammar: ['补全：Tu ___ quel âge ?（你多大？）', ['as'], 'avoir 与 tu 对应 as；quel âge 用于询问年龄。'],
    examAudio: ['Bonjour, je m’appelle Luc. J’ai vingt ans. Je suis étudiant.', 'Luc 的年龄与身份是？', ['二十岁，学生','三十岁，医生','二十岁，医生'], '二十岁，学生']
  },
  {
    id: 'fr03', title: '家人和朋友', goal: '冠词、物主形容词、性数配合',
    grammar: '名词有阴阳性。un/une/des 表示一个／一些，le/la/les 表示特指的“这／那”。元音前 le/la 省音为 l’。复数通常加 s（往往不发音）。mon/ma/mes 表示“我的”，随被拥有的名词变化，而非随拥有者性别变化：mon frère、ma sœur、mes parents。形容词通常随名词配合：petit/petite、grands/grandes。C’est 是“这是”，Ce sont 是“这些是”。',
    pronunciation: 'frère 与 mère 含 è，注意和 été 的 é 区分。sœur 的 œ 是一个元音组合。les amis 常发生联诵，les 的 s 在元音前听起来像 z。不要把所有词末 s 都读出来。',
    vocabulary: [['la mère','母亲'],['le père','父亲'],['la sœur','姐妹'],['le frère','兄弟'],['les parents','父母'],['un ami','一个男性朋友'],['une amie','一个女性朋友'],['petite','小的／矮的（阴性）']],
    sentence: "C'est ma sœur.", sentenceMeaning: '这是我的姐妹。',
    translate: ['这是我的兄弟。', ["C'est mon frère."]],
    grammarChoice: ['选出正确的“我的母亲”。', ['ma mère','mon mère','mes mère'], 'ma mère', 'mère 是阴性单数，用 ma。'],
    grammarText: ['补全：Ce ___ mes parents.（这些是我的父母。）', ['sont'], '复数介绍用 Ce sont；parents 是复数。'],
    listen: ['Voici ma famille. Mon frère s’appelle Paul. Ma sœur s’appelle Julie.', 'Julie 是说话者的谁？', ['姐妹','母亲','男性朋友'], '姐妹'],
    dictation: ['Mon frère.', ['mon frère']],
    reading: ['C’est ma mère. Elle s’appelle Anne. Elle est médecin. Mon père est professeur.', 'Anne 的职业是什么？', ['医生','教师','学生'], '医生'],
    reviewGrammar: ['补全：Elle est ___.（她个子小，使用 petit 的正确形式。）', ['petite'], 'elle 对应阴性形容词 petite。'],
    examAudio: ['C’est mon ami Hugo. Il a vingt ans. Il a une sœur.', 'Hugo 有什么家人？', ['一个姐妹','两个兄弟','一个女儿'], '一个姐妹']
  },
  {
    id: 'fr04', title: '一天的生活', goal: '现在时、时间、否定与日常活动',
    grammar: '规则 -er 动词：parler → je parle、tu parles、il/elle parle、nous parlons、vous parlez、ils/elles parlent。否定把动词放在 ne…pas 中：Je ne travaille pas。元音前 ne→n’。代词式动词：Je me lève（我起床），tu te lèves。时间：Il est huit heures；à huit heures 表示“在八点”。星期：lundi, mardi, mercredi, jeudi, vendredi, samedi, dimanche。',
    pronunciation: 'parle、parles、parlent 在普通现在时中通常同音，书写时仍要配合主语。heures 的 h 不发音，deux heures 有联诵。练习先听懂整点，再听 et demie（半点）。',
    vocabulary: [['travailler','工作'],['étudier','学习'],['manger','吃'],['parler','说话'],['le matin','早晨'],['le soir','晚上'],['huit heures','八点'],['lundi','星期一']],
    sentence: 'Je travaille le matin.', sentenceMeaning: '我早晨工作。',
    translate: ['我不工作。', ['Je ne travaille pas.']],
    grammarChoice: ['nous + parler 的正确形式是？', ['nous parlons','nous parlez','nous parlent'], 'nous parlons', '规则 -er 动词与 nous 配合通常用 -ons。'],
    grammarText: ['补全：Vous ___ français.（使用 parler：你们说法语。）', ['parlez'], 'vous 对应 -ez：parlez。'],
    listen: ['Le lundi, je travaille à huit heures. Le soir, j’étudie le français.', '星期一几点开始工作？', ['八点','十八点','七点'], '八点'],
    dictation: ['Il est huit heures.', ['Il est huit heures.','Il est 8 heures.']],
    reading: ['Je m’appelle Sam. Je me lève à sept heures. Je travaille le matin. Le dimanche, je ne travaille pas.', 'Sam 星期日是否工作？', ['不工作','早晨工作','晚上工作'], '不工作'],
    reviewGrammar: ['补全：Je ___ lève à sept heures.', ['me'], 'se lever 是代词式动词，je 搭配 me。'],
    examAudio: ['Il est neuf heures. Aujourd’hui, nous étudions le français. Nous ne travaillons pas.', '今天他们做什么？', ['学习法语，不工作','工作，不学习','九点吃晚饭'], '学习法语，不工作']
  },
  {
    id: 'fr05', title: '在咖啡馆', goal: '点餐、数量、部分冠词与价格',
    grammar: '可数物品可用 un/une；不确定数量用 du（阳性）、de la（阴性）、de l’（元音前）、des（复数）：du pain、de l’eau。数量后常用 de：un kilo de pommes。否定通常变成 de/d’：Je ne bois pas de café。Je voudrais… 是初学者可直接使用的礼貌点餐句型。Combien ça coûte ? 询问价格。boire：je bois、vous buvez；prendre：je prends、vous prenez。',
    pronunciation: 'eau 发一个类似 o 的元音，不按三个字母分别念。café 末尾 é 要读出；pain 是鼻化元音。deux euros 的两个词通常联诵。',
    vocabulary: [['un café','一杯咖啡'],['un thé','一杯茶'],["de l'eau",'一些水'],['du pain','一些面包'],['une pomme','一个苹果'],["l'addition",'账单'],['un euro','一欧元'],['un kilo','一千克']],
    sentence: 'Je voudrais un café.', sentenceMeaning: '我想要一杯咖啡。',
    translate: ['我想要一杯茶。', ['Je voudrais un thé.']],
    grammarChoice: ['选出正确的“一些水”。', ["de l'eau",'du eau','de la eau'], "de l'eau", 'eau 以元音开头，使用 de l’。'],
    grammarText: ['补全：Je ne bois pas ___ café.', ['de'], '否定句中，部分冠词通常变为 de。'],
    listen: ['Bonjour, je voudrais un café et un verre d’eau, s’il vous plaît.', '客人点了什么？', ['咖啡和水','茶和面包','苹果和茶'], '咖啡和水'],
    dictation: ["L'addition, s'il vous plaît.", ["L'addition, s'il vous plaît."]],
    reading: ['Menu : café 2 euros ; thé 3 euros ; sandwich 5 euros. Le café et le sandwich coûtent 7 euros.', '一杯茶多少钱？', ['3欧元','2欧元','5欧元'], '3欧元'],
    reviewGrammar: ['补全：un kilo ___ pommes', ['de'], '表示明确数量时，数量表达后用 de。'],
    examAudio: ['Le café coûte deux euros. Le thé coûte trois euros. Je prends un thé.', '客人选择的饮品多少钱？', ['三欧元','两欧元','五欧元'], '三欧元']
  },
  {
    id: 'fr06', title: '城市与住处', goal: '问路、位置、交通、房间与疑问句',
    grammar: 'Où est… ? 询问“……在哪里”。Est-ce que… ? 可放在陈述句前构成一般疑问句。位置：à gauche（左）、à droite（右）、devant（前）、derrière（后）、près de（附近）。à+le=au，à+les=aux；de+le=du，de+les=des。Il y a 表示“有”。aller：je vais、tu vas、il va、nous allons、vous allez、ils vont。命令式常见句：Allez tout droit（直走）。',
    pronunciation: 'où（哪里）带重音，与 ou（或者）区别在书写和意义，读音相同。rue 的 u 与 vous 的 ou 读音不同。请反复听 rue 和 vous，观察嘴唇形状。',
    vocabulary: [['la gare','火车站'],['la rue','街道'],['à gauche','向左／在左边'],['à droite','向右／在右边'],['tout droit','一直向前'],['la chambre','房间／卧室'],['la cuisine','厨房'],['le bus','公交车']],
    sentence: 'Je vais à la gare.', sentenceMeaning: '我去火车站。',
    translate: ['车站在哪里？', ['Où est la gare ?']],
    grammarChoice: ['“我去咖啡馆”中 à + le 应怎样写？', ['Je vais au café.','Je vais à le café.','Je vais aux café.'], 'Je vais au café.', 'à 与 le 缩合为 au。'],
    grammarText: ['补全：Il y ___ une cuisine.（有一个厨房。）', ['a'], 'Il y a 是表达“有”的固定结构。'],
    listen: ['Pour aller à la gare, allez tout droit, puis à gauche.', '先直走，然后往哪边？', ['左边','右边','后方'], '左边'],
    dictation: ['La gare est à droite.', ['La gare est à droite.']],
    reading: ['Mon appartement a deux chambres et une cuisine. Il est près de la gare. Je prends le bus pour travailler.', '公寓靠近哪里？', ['火车站','学校','医院'], '火车站'],
    reviewGrammar: ['补全：Nous ___ à la gare.（使用 aller。）', ['allons'], 'aller 与 nous 对应 allons。'],
    examAudio: ['Bonjour, où est le café ? Le café est à droite, près de la gare.', '咖啡馆的位置是？', ['右边，车站附近','左边，车站后面','直走，学校附近'], '右边，车站附近']
  },
  {
    id: 'fr07', title: '喜好、天气与购物', goal: '表达喜好、选择物品、询问尺寸与天气',
    grammar: '表达喜好：J’aime le cinéma，Je n’aime pas le sport。喜好后一般用定冠词。faire：je fais、tu fais、il fait、nous faisons、vous faites、ils font。天气：Il fait beau/froid/chaud，Il pleut。指示形容词：ce livre、cet ami（阳性元音前）、cette robe、ces chaussures。疑问形容词 quel/quelle/quels/quelles 随名词变化。可以用 parce que 说明简单原因。',
    pronunciation: 'chaud 末尾 d 通常不发音；froid 末尾 d 也通常不发音。chaussures 的 ch 类似“sh”，不要读成英语 chair 的起始音。喜好句先听语气，再分辨 aime 与 n’aime pas。',
    vocabulary: [['le cinéma','电影／电影院'],['le sport','运动'],['la musique','音乐'],['une robe','一条连衣裙'],['les chaussures','鞋子'],['bleu','蓝色的（阳性）'],['il pleut','下雨了'],['il fait froid','天气冷']],
    sentence: "J'aime la musique.", sentenceMeaning: '我喜欢音乐。',
    translate: ['我不喜欢运动。', ["Je n'aime pas le sport."]],
    grammarChoice: ['选出正确的“这条连衣裙”。', ['cette robe','ce robe','cet robe'], 'cette robe', 'robe 是阴性单数，用 cette。'],
    grammarText: ['补全：___ taille ?（什么尺码？taille 是阴性。）', ['Quelle'], '阴性单数疑问形容词为 quelle。'],
    listen: ['Il pleut aujourd’hui. Je ne fais pas de sport. J’écoute de la musique.', '说话者今天做什么？', ['听音乐','做运动','买鞋'], '听音乐'],
    dictation: ['Il fait froid.', ['Il fait froid.']],
    reading: ['Je voudrais cette robe bleue. Elle coûte vingt euros. Les chaussures coûtent trente euros.', '连衣裙是什么颜色？', ['蓝色','红色','黑色'], '蓝色'],
    reviewGrammar: ['补全：Vous ___ du sport ?（使用 faire。）', ['faites'], 'faire 与 vous 对应 faites。'],
    examAudio: ['J’aime le cinéma, mais je n’aime pas le sport. Demain, il fait beau.', '说话者不喜欢什么？', ['运动','电影','晴天'], '运动']
  },
  {
    id: 'fr08', title: '周末出行', goal: '日期、近期计划与 A1 综合交流',
    grammar: '近期计划用 aller 的现在时 + 动词原形：Je vais visiter Paris。pouvoir：je peux、vous pouvez；vouloir：je veux、vous voulez。礼貌询问可用 Vous pouvez répéter ?。简单叙述昨天做过的事可用常见复合过去时：J’ai visité Paris（avoir+过去分词）；这里仅识别和练习规则 -er→-é，不扩展到完整过去时体系。日期：le deux mai。月份：janvier, février, mars, avril, mai, juin, juillet, août, septembre, octobre, novembre, décembre。',
    pronunciation: 'train 和 pain 都有鼻化元音，但鼻化不是在元音后额外加一个清楚的 n。visiter 的 -er 与 visité 的 -é 通常同音，因此判断时间还要听 vais 或 ai。',
    vocabulary: [['demain','明天'],["aujourd'hui",'今天'],['hier','昨天'],['un billet','一张票'],['le train','火车'],['visiter','参观'],['mai','五月'],['samedi','星期六']],
    sentence: 'Je vais visiter Paris.', sentenceMeaning: '我打算参观巴黎。',
    translate: ['我想要一张去巴黎的票。', ['Je voudrais un billet pour Paris.']],
    grammarChoice: ['“我们打算参观巴黎”的正确句子是？', ['Nous allons visiter Paris.','Nous allons visitons Paris.','Nous avons visiter Paris.'], 'Nous allons visiter Paris.', '近期将来时为 aller 的变位 + 动词原形。'],
    grammarText: ['补全：Hier, j’ai ___ Paris.（使用 visiter 的过去分词。）', ['visité'], '规则 -er 动词的常见过去分词把 -er 改为 -é。'],
    listen: ['Demain, samedi, je vais à Paris en train. Le train part à neuf heures.', '火车几点出发？', ['九点','七点','十九点'], '九点'],
    dictation: ['Je voudrais un billet.', ['Je voudrais un billet.']],
    reading: ['Bonjour ! Je m’appelle Léa. Samedi, le deux mai, je vais visiter Paris avec ma sœur. Nous prenons le train à huit heures. Je voudrais deux billets.', 'Léa 需要几张票？', ['两张','一张','三张'], '两张'],
    reviewGrammar: ['补全：Vous ___ répéter, s’il vous plaît ?（使用 pouvoir。）', ['pouvez'], 'pouvoir 与 vous 对应 pouvez；这是请求重复时常用的礼貌表达。'],
    examAudio: ['Bonjour, je m’appelle Marie. J’ai trente ans. Demain, je vais à Paris avec ma sœur. Nous prenons le train à huit heures. Je voudrais deux billets, s’il vous plaît.', '哪一项与录音一致？', ['Marie三十岁，和姐妹乘八点的火车去巴黎，需要两张票','Marie二十岁，独自乘九点的火车去巴黎','Marie三十岁，和兄弟乘公交去巴黎'], 'Marie三十岁，和姐妹乘八点的火车去巴黎，需要两张票']
  }
];

const extraVocabulary = [
  [["bonsoir","晚上好"],["bonne nuit","晚安"],["à demain","明天见"],["madame","女士"],["monsieur","先生"],["comment","怎样"],["bien","好"],["enchanté","很高兴认识你（男性说）"]],
  [["le nom","姓名／姓氏"],["le prénom","名字"],["une adresse","一个地址"],["le téléphone","电话"],["dix","十"],["douze","十二"],["quarante","四十"],["cinquante","五十"]],
  [["le fils","儿子"],["la fille","女儿／女孩"],["le mari","丈夫"],["la femme","妻子／女人"],["grand","高大的（阳性）"],["grande","高大的（阴性）"],["jeune","年轻的"],["sympathique","友好的"]],
  [["se lever","起床"],["dormir","睡觉"],["lire","阅读"],["écrire","写"],["midi","中午十二点"],["minuit","午夜十二点"],["dimanche","星期日"],["et demie","半点（时间用语）"]],
  [["le lait","牛奶"],["le fromage","奶酪"],["le riz","米饭／大米"],["le poisson","鱼"],["la viande","肉"],["les légumes","蔬菜"],["le petit-déjeuner","早餐"],["le dîner","晚餐"]],
  [["la salle de bains","浴室"],["le salon","客厅"],["la maison","房子"],["près de","在……附近"],["devant","在……前面"],["derrière","在……后面"],["la pharmacie","药店"],["un hôpital","一家医院"]],
  [["rouge","红色的"],["noir","黑色的（阳性）"],["blanc","白色的（阳性）"],["la taille","尺码／身高"],["cher","贵的（阳性）"],["il fait chaud","天气热"],["il fait beau","天气晴好"],["pourquoi","为什么"]],
  [["janvier","一月"],["février","二月"],["juillet","七月"],["août","八月"],["un hôtel","一家旅馆"],["une réservation","一项预订"],["partir","出发／离开"],["arriver","到达"]]
];
units.forEach((unit, index) => unit.vocabulary.push(...extraVocabulary[index]));
